[project]
name = "mcp-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=5.4.0",
    "mcp[cli]>=1.6.0",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
    "seleniumbase>=4.37.7",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["ipykernel>=6.29.5", "uv>=0.6.16"]

[project.scripts]
work-parser = "job_offer_scrapper:main"
